name: Build APK Kivy
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build APK dengan Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload Hasil APK
        uses: actions/upload-artifact@v4
        with:
          name: Game-Backrooms-APK
          path: ${{ steps.buildozer.outputs.filename }}
